# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a089f0896357f97fd6d4cb49e2f87f3c709ed3a98e0dd143a88bfa6ee8a9673ba75d4a9957a209a2975ef28754cc50e3667fa5ff5181c1f2a688b9e8bb9a94

test:
  secret_key_base: 7952bdd807f984d80598e3fc9b95729ea4e41794e1f85e40205eb04ed4628106c1630be7a289d12fdcd29437c27bd47f2eea05afdc98c8a1e2dbca366862903a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
